version: "3.9"
services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "9000:80"
    volumes:
      - ./www:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
