services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab5_nginx
    ports:
      - "8085:80"    # Изменено с 8080 на 8085
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_pass
    ports:
      - "3308:3306"  # Изменено с 3307 на 3308
    volumes:
      - db_data:/var/lib/mysql  # Добавил volume обратно

  adminer:
    image: adminer
    container_name: lab5_adminer
    restart: always
    ports:
      - "8086:8080"  # Изменено с 8081 на 8086
    depends_on:
      - db

volumes:
  db_data:  # Добавил объявление volume